import { Button } from "@/components/Button";
import { Card } from "@/components/Card";
import { Container } from "@/components/Container";
import { generateImagePreview } from "@/lib/image";
import { generatePostPreview } from "@/lib/ai";
import { getAutomationModules, getSystemStatus } from "@/lib/storage";
import { getAllTrends, getTopTrend } from "@/lib/trends";

function formatDate(value: string) {
  return new Intl.DateTimeFormat("en", {
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit"
  }).format(new Date(value));
}

export default async function HomePage() {
  const [trends, topTrend, preview, image, systemStatus, modules] = await Promise.all([
    getAllTrends(),
    getTopTrend(),
    generatePostPreview(),
    generateImagePreview(),
    getSystemStatus(),
    getAutomationModules()
  ]);

  return (
    <main className="page-shell">
      <Container>
        <section className="hero reveal-up">
          <div className="hero-badge">Premium automation dashboard</div>
          <h1>AI Trend Auto Publisher</h1>
          <p className="hero-subtitle">Automated AI Content Engine</p>
          <p className="hero-description">
            A premium control surface for trend discovery, content generation, creative previews, and publishing workflows.
          </p>
          <div className="hero-actions">
            <Button href="/api/test">Check API</Button>
            <Button href="/history" variant="secondary">
              View History
            </Button>
          </div>
          <div className="hero-stats">
            <div className="hero-stat glass-panel">
              <span>Active modules</span>
              <strong>{modules.length}</strong>
            </div>
            <div className="hero-stat glass-panel">
              <span>Top trend score</span>
              <strong>{topTrend.score}</strong>
            </div>
            <div className="hero-stat glass-panel">
              <span>System state</span>
              <strong>{systemStatus.overall}</strong>
            </div>
          </div>
        </section>

        <section className="dashboard-grid reveal-up delay-1">
          <Card title="Latest Trends" description="Fresh topics ranked for the next publishing window." eyebrow="Trending Topics">
            <div className="trend-list">
              {trends.slice(0, 4).map((trend) => (
                <article key={trend.id} className="trend-item">
                  <div>
                    <h3>{trend.title}</h3>
                    <p>
                      {trend.category} · {trend.source}
                    </p>
                  </div>
                  <div className="trend-meta">
                    <span className="score-pill">{trend.score}</span>
                    <time dateTime={trend.publishedAt}>{formatDate(trend.publishedAt)}</time>
                  </div>
                </article>
              ))}
            </div>
          </Card>

          <Card title="Generated Post Preview" description="A ready-to-review content brief generated by the AI layer." eyebrow="Next Post Preview">
            <div className="preview-block">
              <span className="status-chip status-ready">Draft ready</span>
              <h3>{preview.title}</h3>
              <p>{preview.summary}</p>
              <div className="keyword-row">
                {preview.keywords.map((keyword) => (
                  <span key={keyword} className="keyword-pill">
                    {keyword}
                  </span>
                ))}
              </div>
              <div className="preview-image glass-subpanel">
                <div>
                  <span className="micro-label">Image prompt</span>
                  <p>{image.prompt}</p>
                </div>
                <span className="image-tag">Visual queued</span>
              </div>
            </div>
          </Card>

          <Card title="System Status" description="Operational readiness across the modular publishing stack." eyebrow="System Status">
            <div className="system-stack">
              <div className="system-summary glass-subpanel">
                <div>
                  <span className="micro-label">Overall state</span>
                  <strong>{systemStatus.overall}</strong>
                </div>
                <time dateTime={systemStatus.updatedAt}>{formatDate(systemStatus.updatedAt)}</time>
              </div>
              <div className="module-list">
                {systemStatus.modules.map((module) => (
                  <div key={module.name} className="module-item">
                    <div>
                      <h3>{module.name}</h3>
                      <p>{module.detail}</p>
                    </div>
                    <span className={`status-chip status-${module.status}`}>{module.status}</span>
                  </div>
                ))}
              </div>
            </div>
          </Card>
        </section>
      </Container>
    </main>
  );
}
